import Header from '../components/Header'
import './globals.css'

export const metadata = {
	title: 'Movie DB',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className='text-center bg-gray-800 text-white' >
		<Header/>
				<div>
					<main>{children}</main>
				</div>
			</body>
		</html>
	)
}
